apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
    replicas: 1
    selector:
      app: postgres
    template:
      metadata:
        name: postgres
        labels:
          app: postgres
      spec:
        containers:
          - name: postgres
            image: postgres:12
            ports:
              - containerPort: 5432
            env:
              - name: POSTGRES_USER
                value: todo
              - name: POSTGRES_PASSWORD
                value: verystrongpass
              - name: POSTGRES_DB
                value: todo
  
  
   
